services:
  mysql:
    user: 501:20
    image: mysql:8.0.33
    ports:
      - 13306:3306
    volumes:
      - ../wanted-backend-dev/mysql_docker/data:/var/lib/mysql:rw
      - ../backend-preonboarding/src/main/resources/initdb:/docker-entrypoint-initdb.d
#      - /Volumes/T7/Study/wanted-backend-dev/mysql_docker/data:/var/lib/mysql:rw
#      - /Volumes/T7/Study/backend-preonboarding/src/main/resources/initdb:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: preonboarding
      MYSQL_DATABASE: wanted
